#!/usr/bin/env python
import sys
if len(sys.argv) != 2:
    print("Usage: wrimg file")
    exit(1)
name = sys.argv[1]
empty = bytes(512)
with open(name + ".bin", mode='rb') as file:
    data = file.read()
with open(name + ".img", mode='wb') as file:
    file.write(data)
    for i in range(2880 - 1):
        file.write(empty)
