#!/usr/bin/env python
# write mbr to an empty 1.44MB floppy disk image
import sys

if len(sys.argv) != 4:
    print("Usage: wrimg image bootfile mainfile")
    exit(1)

img_size = 2880 # number of blocks in img
img_name = sys.argv[1]
boot_name = sys.argv[2]
main_name = sys.argv[3]

with open(boot_name, mode='rb') as file:
    boot = file.read()

with open(main_name, mode='rb') as file:
    main = file.read()

with open(img_name, mode='wb') as file:
    file.write(boot)
    file.write(main)
    # fill remaining blocks with zero
    file.write(bytes(2880*512-len(main)-512))
