#!/usr/bin/env python3
# write boot block to an empty 1.44MB floppy disk image
import os
import sys

if len(sys.argv) != 3:
    print("Usage: mkboot image stage0")
    exit(1)

imgsize = 2880 # number of blocks in img
emptyblock = bytes(512)

with open(sys.argv[2], mode='rb') as file:
    boot = file.read()

with open(sys.argv[1], mode='wb') as file:
    file.write(boot)
    # fill remaining blocks with zero
    for i in range(imgsize - 1):
        file.write(emptyblock)
